<?php

namespace Database\Factories\Siasn;

use App\Models\Siasn\SiasnPnsDataUtama;
use Illuminate\Database\Eloquent\Factories\Factory;

class SiasnPnsDataUtamaFactory extends Factory
{
    protected $model = SiasnPnsDataUtama::class;

    public function definition(): array
    {
        return [
            'id' => fake()->uuid(),
            'nipBaru' => fake()->numerify('##################'),
            'nipLama' => fake()->word(),
            'nama' => fake()->name(),
            'gelarDepan' => fake()->word(),
            'gelarBelakang' => fake()->word(),
            'tempatLahir' => fake()->word(),
            'tempatLahirId' => fake()->word(),
            'tglLahir' => fake()->date('d-m-Y'),
            'agama' => fake()->word(),
            'agamaId' => 1,
            'email' => fake()->unique()->safeEmail(),
            'emailGov' => fake()->unique()->safeEmail(),
            'nik' => fake()->word(),
            'alamat' => fake()->word(),
            'noHp' => fake()->word(),
            'noTelp' => fake()->word(),
            'jenisPegawaiId' => '01',
            'mkTahun' => fake()->randomNumber(),
            'mkBulan' => fake()->randomNumber(),
            'jenisPegawaiNama' => fake()->word(),
            'kedudukanPnsId' => fake()->word(),
            'kedudukanPnsNama' => fake()->word(),
            'statusPegawai' => fake()->word(),
            'jenisKelamin' => fake()->word(),
            'jenisIdDokumenId' => fake()->word(),
            'jenisIdDokumenNama' => fake()->word(),
            'nomorIdDocument' => fake()->word(),
            'noSeriKarpeg' => fake()->word(),
            'tkPendidikanTerakhirId' => fake()->word(),
            'tkPendidikanTerakhir' => fake()->word(),
            'pendidikanTerakhirId' => fake()->word(),
            'pendidikanTerakhirNama' => fake()->word(),
            'tahunLulus' => fake()->word(),
            'tmtPns' => fake()->date('d-m-Y'),
            'tmtPensiun' => fake()->date('d-m-Y'),
            'bupPensiun' => fake()->randomNumber(),
            'tglSkPns' => fake()->date('d-m-Y'),
            'tmtCpns' => fake()->date('d-m-Y'),
            'tglSkCpns' => fake()->date('d-m-Y'),
            'instansiIndukId' => fake()->word(),
            'instansiIndukNama' => fake()->word(),
            'satuanKerjaIndukId' => fake()->word(),
            'satuanKerjaIndukNama' => fake()->word(),
            'kanregId' => fake()->word(),
            'kanregNama' => fake()->word(),
            'instansiKerjaId' => fake()->word(),
            'instansiKerjaNama' => fake()->word(),
            'instansiKerjaKodeCepat' => fake()->word(),
            'satuanKerjaKerjaId' => fake()->word(),
            'satuanKerjaKerjaNama' => fake()->word(),
            'unorId' => fake()->word(),
            'unorNama' => fake()->word(),
            'unorIndukId' => fake()->word(),
            'unorIndukNama' => fake()->word(),
            'jenisJabatanId' => fake()->word(),
            'jenisJabatan' => fake()->word(),
            'jabatanNama' => fake()->word(),
            'jabatanStrukturalId' => fake()->word(),
            'jabatanStrukturalNama' => fake()->word(),
            'jabatanFungsionalId' => fake()->word(),
            'jabatanFungsionalNama' => fake()->word(),
            'jabatanFungsionalUmumId' => fake()->word(),
            'jabatanFungsionalUmumNama' => fake()->word(),
            'tmtJabatan' => fake()->date('d-m-Y'),
            'lokasiKerjaId' => fake()->word(),
            'lokasiKerja' => fake()->word(),
            'golRuangAwalId' => fake()->word(),
            'golRuangAwal' => fake()->word(),
            'golRuangAkhirId' => fake()->word(),
            'golRuangAkhir' => fake()->word(),
            'tmtGolAkhir' => fake()->date('d-m-Y'),
            'masaKerja' => fake()->word(),
            'eselon' => fake()->word(),
            'eselonId' => fake()->word(),
            'eselonLevel' => fake()->word(),
            'tmtEselon' => fake()->date('d-m-Y'),
            'gajiPokok' => fake()->word(),
            'kpknId' => fake()->word(),
            'kpknNama' => fake()->word(),
            'ktuaId' => fake()->word(),
            'ktuaNama' => fake()->word(),
            'taspenId' => fake()->word(),
            'taspenNama' => fake()->word(),
            'jenisKawinId' => 1,
            'statusPerkawinan' => fake()->word(),
            'statusHidup' => fake()->word(),
            'tglSuratKeteranganDokter' => fake()->date('d-m-Y'),
            'noSuratKeteranganDokter' => fake()->word(),
            'jumlahIstriSuami' => fake()->randomNumber(),
            'jumlahAnak' => fake()->randomNumber(),
            'noSuratKeteranganBebasNarkoba' => fake()->word(),
            'tglSuratKeteranganBebasNarkoba' => fake()->date('d-m-Y'),
            'skck' => fake()->word(),
            'tglSkck' => fake()->date('d-m-Y'),
            'akteKelahiran' => fake()->word(),
            'akteMeninggal' => fake()->word(),
            'tglMeninggal' => fake()->date('d-m-Y'),
            'noNpwp' => fake()->word(),
            'tglNpwp' => fake()->date('d-m-Y'),
            'noAskes' => fake()->word(),
            'bpjs' => fake()->word(),
            'kodePos' => fake()->word(),
            'noSpmt' => fake()->word(),
            'noTaspen' => fake()->word(),
            'bahasa' => fake()->word(),
            'kppnId' => fake()->word(),
            'kppnNama' => fake()->word(),
            'pangkatAkhir' => fake()->word(),
            'tglSttpl' => fake()->date('d-m-Y'),
            'nomorSttpl' => fake()->word(),
            'nomorSkCpns' => fake()->word(),
            'nomorSkPns' => fake()->word(),
            'jenjang' => fake()->word(),
            'jabatanAsn' => fake()->word(),
            'kartuAsn' => fake()->word(),
        ];
    }
}
